
version: '3.8'

services:
  user-service:
    container_name: user-service
    image: user-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8086
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_H2_CONSOLE_ENABLED=true
    networks:
      - users-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  users-network:
    driver: bridge
